#!/usr/bin/env python3
"""Add per-sample NLL/PPL/DAS fields to Figure 1 GSM8K sampling jsonl files.

DAS follows new_scripts/joint_metrics_parallel.py:
    DAS = log(rho) - NLL

By default, NLL is scored with Qwen2.5-3B for every response, including
responses generated by larger models. This keeps DAS on one common scale and
avoids loading the large generator models. Use --score-with-source-model to
restore per-generator scoring. The input jsonl is not modified; this writes a
new jsonl under each model folder.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import torch
from torch.nn import CrossEntropyLoss
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer

BASE = Path("/common/users/sl2148/Public/yang_ouyang/projects/fact-enhancement")
DATA_DIR = BASE / "new_exps" / "figure1_sampling_data"
DEFAULT_SCORER_MODEL = "Qwen/Qwen2.5-3B-Instruct"

MODEL_FOLDERS = [
    ("Qwen_Qwen2.5-0.5B-Instruct", "Qwen/Qwen2.5-0.5B-Instruct"),
    ("Qwen_Qwen2.5-1.5B-Instruct", "Qwen/Qwen2.5-1.5B-Instruct"),
    ("Qwen_Qwen2.5-3B-Instruct", "Qwen/Qwen2.5-3B-Instruct"),
    ("Qwen_Qwen2.5-7B-Instruct", "Qwen/Qwen2.5-7B-Instruct"),
    ("Qwen_Qwen2.5-14B-Instruct", "Qwen/Qwen2.5-14B-Instruct"),
    ("Qwen_Qwen2.5-32B-Instruct", "Qwen/Qwen2.5-32B-Instruct"),
    ("Qwen_Qwen2.5-72B-Instruct", "Qwen/Qwen2.5-72B-Instruct"),
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=Path, default=DATA_DIR)
    parser.add_argument("--input-name", default="gsm8k_samples.jsonl")
    parser.add_argument("--output-name", default="gsm8k_samples_with_das.jsonl")
    parser.add_argument(
        "--scorer-model",
        default=DEFAULT_SCORER_MODEL,
        help="LM used to compute NLL/PPL/DAS for every response.",
    )
    parser.add_argument(
        "--score-with-source-model",
        action="store_true",
        help="Load each sample's generator model for NLL instead of the fixed scorer model.",
    )
    parser.add_argument(
        "--models",
        nargs="*",
        default=["all"],
        help="Model folder names to score, or 'all'.",
    )
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--max-length", type=int, default=8192)
    parser.add_argument("--dtype", choices=("float16", "bfloat16", "float32"), default="float16")
    parser.add_argument(
        "--device-map",
        default="auto",
        help="Transformers device_map. Use 'single' for cuda:0, 'cpu' for CPU.",
    )
    parser.add_argument(
        "--limit-records",
        type=int,
        default=None,
        help="Debug only: score at most this many jsonl records per model.",
    )
    return parser.parse_args()


def select_models(names: list[str]) -> list[tuple[str, str]]:
    if names == ["all"]:
        return MODEL_FOLDERS
    wanted = set(names)
    out = [pair for pair in MODEL_FOLDERS if pair[0] in wanted or pair[1] in wanted]
    missing = wanted - {p[0] for p in out} - {p[1] for p in out}
    if missing:
        raise SystemExit(f"Unknown model(s): {', '.join(sorted(missing))}")
    return out


def load_records(path: Path, limit: int | None) -> list[dict]:
    records = []
    with open(path, encoding="utf-8") as f:
        for i, line in enumerate(f):
            if limit is not None and i >= limit:
                break
            records.append(json.loads(line))
    return records


def score_texts(texts: list[str], tokenizer, model, max_length: int) -> list[tuple[float, float]]:
    enc = tokenizer(
        texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=max_length,
    )
    enc = {k: v.to(model.device) for k, v in enc.items()}
    with torch.inference_mode():
        outputs = model(**enc)
        logits = outputs.logits[:, :-1, :]
        labels = enc["input_ids"][:, 1:]
        attn = enc["attention_mask"][:, 1:].bool()

        loss_fct = CrossEntropyLoss(reduction="none")
        losses = loss_fct(logits.reshape(-1, logits.size(-1)), labels.reshape(-1))
        losses = losses.reshape(labels.shape)

        nlls = []
        ppls = []
        for row_loss, row_mask in zip(losses, attn):
            valid = row_loss[row_mask]
            if valid.numel() == 0:
                nll = float("nan")
            else:
                nll = float(valid.mean().item())
            nlls.append(nll)
            ppls.append(float(math.exp(nll)) if math.isfinite(nll) else float("nan"))
    return list(zip(nlls, ppls))


def load_model(model_id: str, args: argparse.Namespace):
    tokenizer = AutoTokenizer.from_pretrained(model_id, trust_remote_code=True)
    tokenizer.padding_side = "right"
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token = tokenizer.eos_token

    dtype = {
        "float16": torch.float16,
        "bfloat16": torch.bfloat16,
        "float32": torch.float32,
    }[args.dtype]

    if args.device_map == "cpu":
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            torch_dtype=torch.float32,
            trust_remote_code=True,
            device_map={"": "cpu"},
        )
    elif args.device_map == "single":
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            torch_dtype=dtype,
            trust_remote_code=True,
            device_map={"": "cuda:0"},
        )
    else:
        model = AutoModelForCausalLM.from_pretrained(
            model_id,
            torch_dtype=dtype,
            trust_remote_code=True,
            device_map=args.device_map,
        )
    model.eval()
    return tokenizer, model


def score_model(
    folder: str,
    generator_model_id: str,
    scorer_model_id: str,
    tokenizer,
    model,
    args: argparse.Namespace,
) -> Path:
    in_path = args.data_dir / folder / args.input_name
    out_path = args.data_dir / folder / args.output_name
    if not in_path.is_file():
        raise FileNotFoundError(in_path)

    records = load_records(in_path, args.limit_records)

    # Flatten sample references so we can batch score while preserving jsonl shape.
    refs: list[tuple[dict, dict]] = []
    texts: list[str] = []
    for rec in records:
        for sample in rec.get("samples", []):
            refs.append((rec, sample))
            texts.append(sample.get("response", ""))

    for start in tqdm(range(0, len(texts), args.batch_size), desc=folder):
        batch_texts = texts[start:start + args.batch_size]
        batch_scores = score_texts(batch_texts, tokenizer, model, args.max_length)
        for (_, sample), (nll, ppl) in zip(refs[start:start + args.batch_size], batch_scores):
            sample["nll"] = round(nll, 6) if math.isfinite(nll) else None
            sample["ppl"] = round(ppl, 6) if math.isfinite(ppl) else None
            rho = float(sample["density_rho"])
            sample["das"] = round(math.log(rho) - nll, 6) if math.isfinite(nll) and rho > 0 else None
            sample["das_scorer_model"] = scorer_model_id

    for rec in records:
        rec["das_scorer_model"] = scorer_model_id
        rec["generator_model_id"] = generator_model_id

    with open(out_path, "w", encoding="utf-8") as f:
        for rec in records:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")
    return out_path


def main() -> None:
    args = parse_args()
    selected = select_models(args.models)

    if args.score_with_source_model:
        for folder, generator_model_id in selected:
            print(f"Scoring {folder} with source model {generator_model_id}")
            tokenizer, model = load_model(generator_model_id, args)
            out_path = score_model(
                folder,
                generator_model_id,
                generator_model_id,
                tokenizer,
                model,
                args,
            )
            print(f"Saved: {out_path}")
            del model
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
        return

    print(f"Loading fixed DAS scorer: {args.scorer_model}")
    tokenizer, model = load_model(args.scorer_model, args)
    for folder, generator_model_id in selected:
        print(f"Scoring {folder} responses with {args.scorer_model}")
        out_path = score_model(
            folder,
            generator_model_id,
            args.scorer_model,
            tokenizer,
            model,
            args,
        )
        print(f"Saved: {out_path}")


if __name__ == "__main__":
    main()
